# Python Practical code

In [8]:
print("1. Celsius to Fahrenheit.")
print("2. Fahrenheit to Celsius.")
choice = int(input("Enter your choice : "))
if choice == 1:
    celsius = float(input("Enter temperature in celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print('%0.2f Celsius is: %0.2f Fahrenheit' %(celsius, fahrenheit))

elif choice == 2:
    fahrenheit = float(input("Enter temperature in fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print('%0.2f Fahrenheit is: %0.2f Celsius' %(fahrenheit, celsius))
else:
    print("Invalid Choice")

1. Celsius to Fahrenheit.
2. Fahrenheit to Celsius.
Enter your choice : 2
Enter temperature in fahrenheit: 10
10.00 Fahrenheit is: -12.22 Celsius


In [3]:
mark_1 , mark_2 , mark_3 = [eval(x) for x in input("Enter marks of three subjects (seperated by comma) : ").split(",")]
Total_marks = mark_1 + mark_2 + mark_3
Average = Total_marks/3
Percentage = (Total_marks/300)*100
print(Percentage)
if Percentage >= 80:
    print("Grade A")
elif Percentage >= 70:
    print("Grade B")
elif Percentage >= 60:
    print("Grade c")
elif Percentage >= 40:
    print("Grade D")
else:
    print("Grade E")

Enter marks of three subjects (seperated by comma) : 90,80.5,60
76.83333333333333
Grade B


In [7]:
import math

def area_rectangle(length, breadth):
    area = length * breadth
    return area

def area_square(side):
    area = pow(side,2)
    return area

def area_circle(r):
    per = (math.pi * r * r)
    return round(per, 2)

def area_triangleSide(a, b, c):
    s = (a + b + c) / 2
    area = math.sqrt(s * (s - a) * (s - b) * (s - c))
    return round(area,2)

#main

print("On which geometric shape would you like to operate on?")
print("1. Rectangle ")
print("2. Square ")
print("3. Circle ")
print("4. Triangle ")

inp = int(input("Enter your choice(1-4) : "))

if(inp == 1):
    a = float(input("Enter the length of the rectangle: "))
    b = float(input("Enter the breadth of the rectangle: "))
    res = area_rectangle(a,b)
    print("Area of rectangle with sides",a,",",b," is ",res)

elif(inp == 2):
    a = float(input("Enter the side of the square: "))
    res = area_square(a)
    print("Area of square with side",a," is ",res)

elif(inp == 3):
    a = float(input("Enter the radius of the circle: "))
    res = area_circle(a)
    print("Area of the circle with radius",a," is ",res)

elif(inp == 4):
    a = float(input("Enter the side 1 of triangle: "))
    b = float(input("Enter the side 2 of triangle: "))
    c = float(input("Enter the side 3 of triangle: "))
    res = area_triangleSide(a, b, c)
    print("Area of triangle with sides:",a,",",b,",",c," is ",res)
    
else:
    print("Invalid Input !!!")

On which geometric shape would you like to operate on?
1. Rectangle 
2. Square 
3. Circle 
4. Triangle 


KeyboardInterrupt: Interrupted by user

In [40]:
# Procedural Approach

n = int(input("Enter the number of nth terms to display: "))
a = 0
b = 1

for i in range(1, n+1):
    c = a + b
    print(a, end=" ")
    a = b
    b = c
print()

Enter the number of nth terms to display: 9
0 1 1 2 3 5 8 13 21 


In [43]:
# Functional Approach
def fibonacci_sequence(n):
    a = 0
    b = 1

    for i in range(1, n):
        c = a + b
        print(a, end=" ")
        a = b
        b = c
    return a

# main
print(fibonacci_sequence(9))


0 1 1 2 3 5 8 13 21


In [5]:
# Procedural Approach
num = int(input("Enter a number: "))    
fact = 1    
if num < 0:    
    print(" Factorial does not exist for negative numbers")    
elif num == 0:    
    print("The factorial of 0 is 1")    
else:    
    for i in range(1,num + 1):    
        fact = fact*i    
    print(f"The factorial of {num} is {fact}")    

Enter a number: 6
The factorial of 6 is 720


In [6]:
# Functional Approach
def factorial(n):
    if (n==1 or n==0):
        return 1
    else:
        return n * factorial(n - 1) 

# main
number = int(input("Enter number :"))
print("Factorial of",number,"is :",factorial(number))


Enter number :6
Factorial of 6 is : 720


In [17]:
# using List
a = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
b = [[1,2,3],
    [4,5,6],
    [7,8,9]]

for i in range(len(a)):   
    for j in range(len(a[0])):
        result[i][j] = a[i][j] + b[i][j]
for i in result:
    print(i)

[2 4 6]
[ 8 10 12]
[14 16 18]


In [13]:
#using numpy
import numpy as np
  
a = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
b = [[1,2,3],
    [4,5,6],
    [7,8,9]]
 
result = np.array(a) + np.array(b)
 
print(result)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [18]:
import mysql.connector
 
[str(x) for x in input("Enter localhost , username , password , database_name (seperated by comma) : ").split(",")]
mydb = mysql.connector.connect(
  host = "localhost",
  user = "username",
  password = "password",
  database = "database_name"
) 

ModuleNotFoundError: No module named 'mysql'